#!/bin/bash

#SBATCH --account=em76
#SBATCH --job-name=array
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=8000
#SBATCH --time=0-00:05:00
#SBATCH --mail-user=adam.irving@monash.edu
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --array=1-500

module load stata/16u2021

stata-mp risk_equations.do dvd_method dvd_pre 2010 2025 1 ${SLURM_ARRAY_TASK_ID} ${SLURM_ARRAY_TASK_ID}