#!/bin/bash

#SBATCH --account=em76
#SBATCH --job-name=array
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=8000
#SBATCH --time=0-00:20:00
#SBATCH --mail-user=adam.irving@monash.edu
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --array=1-500

module load stata/16u2021

stata-mp analyses/dvd_method/dvd_method.do ${SLURM_ARRAY_TASK_ID} ${SLURM_ARRAY_TASK_ID}